Note App
Odile078/react-scrimba-projects pull request #7
Opened 2023-03-09 15:34 UTC by Odile078

# P.R. Description
Implementation of Note app.
## Completed Tasks
- [x] Add page design
- [x] Add create, update and delete functionality
## Live link
[link](https://deploy-preview-3--magenta-moonbeam-158f96.netlify.app/)
## Testing
Run the command below to open the landing page on a local server for testing
- npm install
- npm run dev

2023-03-10 10:13 UTC, mutesialine requested changes
Great Job @Odile078  , Only a few things to change for the code to look more better.

2023-03-10 10:13 UTC, mutesialine commented on src/main.jsx
> +import React from "react";
Better to remove this import of react since the new version of react can handle it by itself

2023-03-10 10:13 UTC, mutesialine commented on src/main.jsx
>    </React.StrictMode>,
Also  you can change this `<React.strictMode>` to  named export .   [here](https://medium.com/@etherealm/named-export-vs-default-export-in-es6-affb483a0910) the link can guide you

2023-03-13 10:17 UTC, mutesialine approved these changes

2023-03-13 10:38 UTC, closed without merging

2023-03-13 10:39 UTC, Odile078 commented
This pr was created on opened on the wrong branch, which is why it's being closed. It should have been from dev-note-app to note-app instead of dev-note-app to main branch